### PR TITLE
[CORE-1264] Differentiate between failures in Terragrunt commands vs rest of pipelines

### PR DESCRIPTION
**Pull request by infraredgirl**
Before this, if a pipelines run would fail, a comment would get added to the PR stating that the Terragrunt command failed, regardless of where the failure happened in the pipelines run.

With this change, we are now adding up to two different comments to the PR:
1. First comment exposes the result of the Terragrunt command (e.g. "Terragrunt plan succeeded or failed")
2. Second comment only gets added if another step in the pipelines run fails. For each such failing step, a link is added to the position of that step in the logs.

Here's an example of what will now happen if e.g. Terragrunt plan succeeds, but there are failing steps after that in the pipeline:

image

Direct link to example: https://github.com/gruntwork-io-team/dogfood-infrastructure-live/pull/253#issuecomment-1724513578.

### CODE REVIEW

**Review by MoonMoon1919 — APPROVED** [review]

**Comment by josh-padnick** [comment]
@infraredgirl Thanks for sharing! I found https://github.com/gruntwork-io-team/dogfood-infrastructure-live/pull/253#issuecomment-1726639311 as a way to try this out in action.

To be clear, is the second type of error expected to never occur, but will only show up if the Pipelines tool has an error? If so, then I think the functionality you've implemented works great, but we need to tweak the UX here.

First, we should make it clear that this was an unexpected error due to Pipelines, not the customer's own configuration. Here's a recommended set of text to update to:
image

Second, what information do we (Gruntwork) need in order to be able to reproduce or diagnose the issue? Is it enough to send the log files? Should the customer send just the error, or the whole log file? Will the log file contain sensitive information? In short, I'd like to think through the whole problem here and make sure that we close the full loop, which I see as:

- Customer experiences error
- Somehow Gruntwork is notified of this error (do we support that now? If not, we should create a separate story for that)
- Customer sends Gruntwork all relevant information (or could we do that automatically if telemetry is enabled)
- Gruntwork reviews the error, makes a fix, and pushes out a change to the customer

We do need to stay within the scope of this story, but we should find out if we'll get notified if an error occurs or if the customer needs to do something. Based on that, we can update the message and call-to-action we give to the user.

**Comment by infraredgirl** [comment]
> To be clear, is the second type of error expected to never occur, but will only show up if the Pipelines tool has an error? If so, then I think the functionality you've implemented works great, but we need to tweak the UX here.
> 

The second type of error will show up if any step, other than the Terragrunt step, of the Pipelines run fails. That can mean a bug in Pipelines itself, but it can also be for other reasons (e.g. authentication to AWS failed).

> First, we should make it clear that this was an unexpected error due to Pipelines, not the customer's own configuration. Here's a recommended set of text to update to: image
> 
I'll hold off on doing this update, since the error would not definitely be a Pipelines bug, but let me know if you have other suggestions!
> Second, what information do we (Gruntwork) need in order to be able to reproduce or diagnose the issue? Is it enough to send the log files? Should the customer send just the error, or the whole log file? Will the log file contain sensitive information? In short, I'd like to think through the whole problem here and make sure that we close the full loop, which I see as:
> 
> * Customer experiences error
> * Somehow Gruntwork is notified of this error (do we support that now? If not, we should create a separate story for that)
> * Customer sends Gruntwork all relevant information (or could we do that automatically if telemetry is enabled)
> * Gruntwork reviews the error, makes a fix, and pushes out a change to the customer
> 
> We do need to stay within the scope of this story, but we should find out if we'll get notified if an error occurs or if the customer needs to do something. Based on that, we can update the message and call-to-action we give to the user.

Sending over the whole log file should probably do it. Secrets are obscured in the GH Actions logs output, so it shouldn't be a concern. We don't have any automation for this as of now, so that would be a separate story.

**Comment by josh-padnick** [comment]
@infraredgirl Thanks for the clarifications! Is there any way we could distinguish an error that occurred due to something the customer/user controls, versus an error in the Pipelines tool itself?

Also, if the `plan` or `apply` yields an error, does that show up here, or as a failed plan/apply? Essentially, I want to be clear on the different categories of errors that could occur and how we handle each. It makes sense to me that all issues with plan/apply would show up in the plan/apply comment, but I'm still unclear as a user on what "Pipelines Run Failed" means, and if that's my fault or the vendor's fault.

**Comment by josh-padnick** [comment]
> I don't think we can make such a distinction programmatically, since all those errors are just errors in the steps of the Pipelines workflows.

You know, I'd love to have a library of "pre-flight checks" that we run as part of each pipeline run. If one of those fails, we could then display a clean error message. For example, if you're not authenticated to AWS, show the comment and even include the resolution.

But that's definitely out of scope for this story, so for now I'm thinking of this as an "unexplained error", and I think the original wording you've got is pretty good. Therefore, I think we can merge this and mark it done!

As one final comment, why did the GitHub Action workflow keep running even though there was an error? Does each step run, even if there's an error in the prior step?

**Comment by infraredgirl** [comment]
> why did the GitHub Action workflow keep running even though there was an error? Does each step run, even if there's an error in the prior step?

It depends - some of the workflows have subsequent steps that we need to run even if a previous step fails. The example is the "Run terragrunt" step - if we fail the whole workflow on that step failure, then the subsequent step that posts the PR comment will never happen. So in some cases we are explicitly configuring the steps to run regardless of the failure of the previous steps, using the `always()` function (see [example here](https://github.com/gruntwork-io/pipelines-dispatch/blob/main/action.yml#L171)).

**Comment by infraredgirl** [comment]
Thanks for the reviews - going to merge this in!

**Comment by josh-padnick** [comment]
> It depends - some of the workflows have subsequent steps that we need to run even if a previous step fails. 

This makes sense; thanks!

**Pull request merged**
